name: Rust


on:
  push:
    branches:
      - main
      - 'feature-**'
  pull_request:
    branches:
      - main
      - 'feature-**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup comonent add rustfmt --toolchain nightly-2023-09-18-x86_64-unknown-linux-gnu
          rustup install nightly

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version          

      - name: Lint
        run: |
          ls
          cargo fmt -- --check
          cargo clippy -- -D warnings          

      - name: Test
        run: |
          cargo check
          cargo test --all          

      - name: Build
        run: |
          cargo build --release