name: Rust


on:
  push:
    branches:
      - main
      - 'feature-**'
  pull_request:
    branches:
      - main
      - 'feature-**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update local toolchain
        run: |
          rustup update
          rustup install nightly
          sudo apt-get update
          sudo apt-get install gcc-avr binutils-avr avr-libc gdb-avr avrdude

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version      

      - name: Test
        run: |
          cargo check
          cargo test --all          

      - name: Build
        run: |
          cargo build --release